# Generated by Django 2.2.7 on 2020-02-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='roles',
            field=models.CharField(choices=[('a', 'Author'), ('r', 'Reader'), ('g', 'Anonymous')], default='', max_length=1),
        ),
    ]
